FROM redis


#RUN mkdir -p /usr/local/etc/redis
#WORKDIR /usr/local/etc/redis
#ONBUILD COPY redis.conf /usr/local/etc/redis


#ONBUILD COPY redis.conf /usr/local/etc/redis
#CMD [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

#RUN mkdir -p /usr/local/etc/redis
#CMD [ "ls", "-la", "/usr/local/etc/redis" ]


CMD [ "redis-server" ]

