FROM java:7
#FROM jgrowl/livehq-media:0.3
COPY lib/native/libjingle_peerconnection_so.so /usr/local/lib/libjingle_peerconnection_so.so
ADD target/scala-2.11/media-assembly-1.0.jar /app/media-assembly-1.0.jar

