- name: Configure api
  hosts: all
  sudo: yes

  vars:
    api_env:
      RBENV_ROOT: ~app/.rbenv
      PATH: ~app/.rbenv/shims:~app/.rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

  tasks:
    - apt: name={{item}} state=present
      with_items:
        - vim
        - libsqlite3-dev

#    - file: path=~app/.rbenv owner=app group=app state=directory
#    - file: src=/usr/local/rbenv/versions dest=~app/.rbenv/versions owner=app group=app state=link

#    - gem: name=bundler state=present
#      environment:
#        api_env

#    - gem: name=rails state=present
#      environment:
#          RBENV_ROOT: /usr/local/rbenv
#          PATH: /usr/local/rbenv/shims:/usr/local/rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
#      sudo: yes

#    - command: rbenv rehash
#      environment:
#          RBENV_ROOT: /usr/local/rbenv
#          PATH: /usr/local/rbenv/shims:/usr/local/rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
#      sudo: yes

