name: web
version: 0.0.1
dependencies:
#  polymer: ">=0.13.0 <0.14.0"
#  core_elements: ">=0.2.0 <0.3.0"
#  paper_elements: ">=0.1.0 <0.2.0"
  exportable: ">=0.1.0 <0.2.0"
  browser: any
  angular: ">=0.14.0 <0.15.0"
  satellizer:
    path: /Users/jonathan/code/github.com/jgrowl/satellizer.dart
#    git: git://github.com/jgrowl/satellizer.dart.git
  webrtc-signal:
    path: /Users/jonathan/Code/github.com/jgrowl/livehq/signal/client
  shadow_dom: any
dev_dependencies:
  http_server: any
  unittest: any
transformers:
- angular